var Path = require('path');

function Grunt(grunt) {

	var Configuration = {},
		tasks = [
			'grunt-6to5',
			'grunt-add-comment',
			'grunt-html2js',
			'grunt-contrib-connect'
		];

	for(var i = 0; i < tasks.length; i++)
		grunt.loadNpmTasks(tasks[i]);

	// require('time-grunt')(grunt);

	var pathOption = getPathOption();

	function getPathOption() {
		var pathOption = false;

		if(grunt.option('path')) {

			pathOption = {};
			pathOption.name = Path.normalize(grunt.option('path')).replace(__dirname, '').slice(1);
			pathOption.extension = Path.extname(grunt.option('path'));
		}

		return pathOption;
	}

	Configuration.package = grunt.file.readJSON('package.json');

	Configuration['6to5'] = {
		options: {
			sourceMap: false
		},
		dist: {
			files: [{
				expand: true,
				cwd: __dirname,
				ext: '.js',
				src: ( pathOption ? pathOption.name : ['examples/**/*.es6', 'lib/**/*.es6'] ),
				dest: __dirname
			}]
		}
	};

	Configuration.add_comment = {
		common: {
			options: {
				comments: ['Autogenerated, do not edit. All changes will be undone.'],
				prepend: true,
				syntaxes: {
					'.js': '//'
				}
			},
			files: [{
				expand: true,
				cwd: '',
				src: ( pathOption ? [pathOption.name.replace('.es6', '.js')] : ['lib/**/*.js'] ),
				dest: ''
			}]
		}
	};

	Configuration.html2js = {
		options: {
			quoteChar: '\'',
			indentString: '\t',
			singleModule: true,
			target: 'js',
			module: 'Dashydash-templates',
			base: __dirname + '/templates'
		},
		app: {
			src: [__dirname + '/templates/**/*.jade'],
			dest: __dirname + '/lib/dashydash-templates/core.js'
		}
	};


    Configuration.connect = {
		options: {
			port: 9000,
			hostname: 'localhost'
		},
		dev: {
			options: { open: true }
		}
	};


	grunt.initConfig(Configuration);

	grunt.registerTask('es6', ['6to5:dist', 'add_comment']);
	grunt.registerTask('dev', ['6to5:dist', 'html2js', 'connect']);
}

module.exports = Grunt;